### ISSUE TITLE
This webpage is not available ERR_CONNECTION_TIMED_OUT

### ISSUE THREAD

**Issue by PatrickJoannisse** [scotch-io/scotch-box#142]
So I've been having this issue for a while now. I don't know how but sometimes after a while it would fix itself. At first I thought it was my host but my host is fine. Basically I called it rpgcms.dev and I'm pointing to the default IP.

If I ssh into the box and curl localhost, it works. If I curl from outside the box, I get a timed out error. 

I'm on Windows running latest scotch box. I searched pretty much everywhere and everyone suggested the following:
 - vagrant provision
 - vagrant reload
 - double check the host file
 - empty your browser cache and try again
 - destroy and vagrant up again

I tried everything. I have no clue what's going on. It was working fine but I restarted my PC and now just can't connect.

**Comment by ncerminara** [comment]
Hey Patrick. What you mean cURL outside the box?

**Comment by CrazyGentleMan** [comment]
I have the exact problem, no matter what I do, even changing the IP in the Vagrantfile, I keep getting "The connection has timed out The server at 192.168.33.10 is taking too long to respond."

**Comment by ncerminara** [comment]
Hey guys - this makes total sense if we think this through. I understand what you're asking now.

On your **laptop**, you made a change to your host file. This change is saying: "Yo Laptop, all network requests to `rpgcms.dev` need to go to IP address `192.168.33.10`. So from your **laptop** if you visit the URL `rpgcms.dev` it will go to `192.168.33.10`.

Okay, cake.

But, if you're **from the server** and visit `rpgcms.dev` it's going to respond with "Yo WTF is that it's not a valid URL. The DNS lookup for this is failing". This is because the **server** / Virtual Machine (your Scotch Box) doesn't inherit the custom host files from your **laptop**.

For example, if you did cURL with the IP `192.168.33.10`, it would work.

If you get where I'm going. The easiest fix is to update your VM's host file as well:

```
vagrant ssh
vim /etc/hosts
# Add this to the bottom
192.168.33.10 rpgcms.dev
```

Then rerun the command and it will work.

**Comment by CrazyGentleMan** [comment]
I didn't change the hosts neither on my local machine nor on the virtual machine, I can't access the IP directly `192.168.33.10`. 
I tried to add `192.168.33.10 whatever.dev` to the bottom for both hosts files and still the same problem.

**Comment by ncerminara** [comment]
Okay - you have a different issue than @PatrickJoannisse.

Open VirtualBox. Is a VM running? Do you have more than one?

**Comment by PatrickJoannisse** [comment]
@ncerminara I fixed it, but not like that. What did it was to add this to my vagrantfile

 > config.vm.network "forwarded_port", guest: 80, host: 8080

**Comment by CrazyGentleMan** [comment]
@ncerminara Yes the VM is running, and it's the only one.
@PatrickJoannisse I added it to Vagrantfile and provisioned it, but still.
```
==> default: Forwarding ports...
    default: 80 => 8080 (adapter 1)
    default: 22 => 2222 (adapter 1)
```

**Comment by CrazyGentleMan** [comment]
[The Problem](http://i.imgur.com/S73tvOS.png)

**Comment by tgroff** [comment]
I had this issue as well with Windows 10, Virtualbox 5.12, and Vagrant 1.8.1, very frustrating. It's not a scotchbox issue though, it's Virtualbox. I downgraded to Virtualbox 5.10 and everything works fine now with the exact same config files. I upgraded to Virtualbox 5.12, and networking was broken again.

The point being - if you can't ping the box IP from the command line, it's probably a Virtualbox networking issue.  The issue was further confused by the fact that vagrant ssh worked fine, and `ifconfig` showed the proper IP address. If that is the case for anyone visiting this thread - try downgrading to a lower Virtualbox version temporarily to see if that easily fixes your issue.

**Comment by ncerminara** [comment]
Okay - can you downgrade to Vagrant 1.7x? I haven't had a chance to investigate but know VirtualBox 5.0 and it work

**Comment by tgroff** [comment]
Hi @ncerminara, now I have no idea what was causing the previous inaccessible problem. I downgraded to Vagrant 1.7.4 with VirtualBox 5.12, and everything worked fine. I was able to ping, and access via web browser, the local scotchbox.

Then I upgraded to Vagrant 1.8.1 with VirtualBox 5.12, and now the scotchbox is perfectly accessible, even though this exact configuration didn't work before.

**Comment by cjduncana** [comment]
I wonder if this is the same thing that is happening at issue #169 ?

**Comment by AtAFork** [comment]
@PatrickJoannisse thank you so much for the `config.vm.network "forwarded_port", guest: 80, host: 8080` suggestion! That, in addition to including `192.168.33.10       lazy.dev` in my `hosts` file on my Windows host finally fixed it for me (after many hours struggling).

**Comment by vbroskas** [comment]
@AtAFork @whatnickcodes @PatrickJoannisse 

OK im having the same problem, and unfortunately I'm pretty new to VM/ScotchBox stuff, so I apologize in advance for anything stupid I'm doing.  Right now when I try and access the project via: http://192.168.33.10/ I get the timed out error like everyone else.

This is what my windows host file looks like. I just followed the instructions found here:
https://support.rackspace.com/how-to/modify-your-hosts-file/
So I hope I did it correctly. What you see in the image I just copied from an entry already in there and added the IP: http://192.168.33.10/
![win hosts file](https://cloud.githubusercontent.com/assets/15919760/20234496/938e2a12-a839-11e6-97fc-3f9dc5b43ba5.JPG)


This is what my Vagrantfile currently looks like, after adding in:
`config.vm.network "forwarded_port", guest: 80, host: 8080`
![vagrantfile](https://cloud.githubusercontent.com/assets/15919760/20234502/b043b956-a839-11e6-9322-e8f0e6541efa.JPG)

Does anyone have any idea what might still be wrong? Could this be a problem with my virtual box?

Thanks in advance for any help you can offer, I greatly appreciate it!

**Comment by AtAFork** [comment]
@vbroskas also new to VM/Scotch Box myself, I changed my `synced_folder` line to read:

 `config.vm.synced_folder "./public", "/var/www", :mount_options => ["dmode=777", "fmode=666"]`

I think that was a fix for a different issue (where the `Index Of /` page was showing up instead of my wordpress content). Also did you try `vagrant halt` and then `vagrant up` again after you made that addition to your Vagrantfile?

Other than that not sure I can be of much help.

**Comment by dnspnjrs** [comment]
Similar issue for me here. same "connection time out". tried @AtAFork solution but doesn't seem to do much. Running on el captan. I hope there will be a solution soon

**Comment by octoxan** [comment]
I'm running into this same issue on Ubuntu 17.04. Vagrant Up throws no errors but I can never access 192.168.33.10. Just loads for forever in the browser.

**Comment by tylerlindell** [comment]
This is my novice solution. If there is a better way, I'm all ears :-)

I was having the same issue and what I had to do was modify my Vagrantfile:
following this answer: [http://stackoverflow.com/a/43213075/3187749](http://stackoverflow.com/a/43213075/3187749)
```
config.vm.network :forwarded_port, guest: 80, host: 4567, host_ip: "127.0.0.1", auto_correct: true
```

then i just ran `vagrant reload` and everything seemed to be good for me on `http://127.0.0.1:4567/`

**Comment by pjhernandez18** [comment]
@tylerlindell just used your solution. 

That did it for me, thank you!
