### ISSUE TITLE
192.168.33.10 redirecting to non dev site

### ISSUE THREAD

**Issue by rocketpastsix** [scotch-io/scotch-box#179]
Ive tried it in Safari and Firefox, both standard and incognito. 

Usually when I hit 192.168.33.10, its just a "page not found" error. However tonight it has started resolving to some page about printers. Screenshot here.

<img width="1440" alt="screen shot 2016-02-03 at 10 44 57 pm" src="https://cloud.githubusercontent.com/assets/4731244/12805265/f23ed958-cac7-11e5-81ad-cf2d795500a1.png">

Ive tried moving the vagrant file to 192.168.33.11 and yet it still lands on this page.

**Comment by rocketpastsix** [comment]
Just to make sure I don't leave anything out, I have never seen this page before. Also, I don't own any Canon printer. It just started happening about an hour ago. Ive used the Scotch Box vagrant file for over a year and its always worked perfectly, so this is an interesting problem to run into.

**Comment by ncerminara** [comment]
What happens if you get off your current network and connect? Either without wifi or a different network. This is crazy and makes no sense ha



On February 3, 2016 at 10:47:12 PM EST, Matt Trask <notifications@github.com> wrote:Ive tried it in Safari and Firefox, both standard and incognito.   Usually when I hit 192.168.33.10, its just a "page not found" error. However tonight it has started resolving to some page about printers. Screenshot here.    Ive tried moving the vagrant file to 192.168.33.11 and yet it still lands on this page.   —Reply to this email directly or view it on GitHub.

**Comment by rocketpastsix** [comment]
Let me try. One minute

**Comment by ncerminara** [comment]
Also what happens if you visit that IP address with all Vagrant boxes removed/destroyed



On February 3, 2016 at 11:00:06 PM EST, Matt Trask <notifications@github.com> wrote:Let me try. One minute   —Reply to this email directly or view it on GitHub.

**Comment by rocketpastsix** [comment]
Just tried with no internet, both Safari and Firefox. Both could not resolve the IP of the vagrantfile. Then I turned the internet back on and it still didnt resolve 192.168.33.10. 

Then I thought it could be my VPN which I was on for work, but I turned that off and nothing happened. 

Havent destroyed or removed boxes, will have to try tomorrow. Catching plane early in the morning for SunshinePHP
