### ISSUE TITLE
Serving the root folder?

### ISSUE THREAD

**Issue by fuzzy76** [scotch-io/scotch-box#184]
I would love to use scotch-box when doing one-off PHP stuff, often consisting of just a couple of files. But for these small projects, the "public" folder really feels superfluous. All I want is to be able to drop the scotch-box Vagrantfile as-is into my existing repository.

**Comment by doctorallen** [comment]
Update the vhost `/etc/apache2/sites-available/000-default` and remove the public directory. Then restart apache.

**Comment by ncerminara** [comment]
This is done by design. A lot of applications actually have code above the root public folder (security) where the assets are only served.

You can either use the recommended setup, change it manually each time, or with provisioning (https://scotch.io/bar-talk/announcing-scotch-box-2-0-our-dead-simple-vagrant-lamp-stack-improved#changing-/public-to-/public_html)

**Comment by ncerminara** [comment]
So for you, it would be something like this:

```
config.vm.provision "shell", inline: <<-SHELL
    rm -rf /var/www/public
    sudo sed -i s,/var/www/public,/var/www,g /etc/apache2/sites-available/000-default.conf
    sudo sed -i s,/var/www/public,/var/www,g /etc/apache2/sites-available/scotchbox.local.conf
    sudo service apache2 restart
SHELL
```

**Comment by steveooo9** [comment]
@whatnickcodes What the version for this code snippet for Scotch Box Pro? I see that there isn't any scotchbox.local.conf...
