### ISSUE TITLE
PPA of php5-comon has been deprecated!

### ISSUE THREAD

**Issue by indrakaw** [scotch-io/scotch-box#257]
Help! What should I do? 
It happened when upgrade packages.

![screenshot from 2016-09-18 13-48-52](https://cloud.githubusercontent.com/assets/9590878/18806557/f6e1324e-825a-11e6-95cd-38a3781129d5.png)
Note: I haven't perform instruction above.

Here's path of php:

```
vagrant@scotchbox:~$ php -v
PHP 5.6.26-1+deb.sury.org~trusty+1 (cli) 
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2016, by Zend Technologies
vagrant@scotchbox:~$ which php
/usr/bin/php
```

**Comment by maxpou** [comment]
Sorry, 
It's maybe too late.

Why you didn't follow this instructions? For me, everything is clear!
(By the way, I'm agree that Scotch box really need an upgrade!)

**Comment by indrakaw** [comment]
I followed instructions and its ~~running smoothly~~, no it isn't. I got few broken dependencies.

**Comment by maxpou** [comment]
Please, give us more details!

In my case, I switch to PHP7. There is [not a lot of backward incompatibilities](http://php.net/manual/en/migration70.incompatible.php). Instructions are in the end of the README.md

**Comment by erronjason** [comment]
Howdy there. I've been troubleshooting this for several hours now, and may have some light to shed.

First of all, the PPA was indeed deprecated. The maintainer (Ondřej Surý) [speaks to this on his Patreon](https://www.patreon.com/posts/now-is-time-to-7009050), and as of the 31st of Oct, the repo now 404's. The suggestion to use a different version (or stay on the same one) is unfortunately not there any longer.

The "update" process for current boxes, would be something to the likeness of:
```bash
sudo rm -f /etc/apt/sources.list.d/ondrej-php5-5_6-trusty.list
sudo LC_ALL=en_US.UTF-8 add-apt-repository -y ppa:ondrej/php
```

The underlying issue with this solution is that now all modules that relied on php5-common won't allow themselves to be installed, citing the version disparity between the installed and repo versions. This of course breaks all current environments that rely on the ability to install a php module via apt since the 31st. At the time of writing, this has been an issue for ten days.

For my purposes, I needed a way for a *nix environment to connect to MSSQL via PHP. Due to this issue, I'm unable to install the "php5-mssql" package at all. I've attempted to seek Microsoft's linux driver, but that's only available for Ubuntu 15.04+.

My suggestion is to first reconfigure (or republish) the vagrant box with the new repo, and then consider the possibility of upgrading the environment to 16.04. The latter being a highly subjective opinion, yes, but many tools only check two versions back and disallow older releases otherwise. It's status as an LTS doesn't mean non-Canonical vendors will respect it (see above for an example).

Because my project depends on this, and I'd like to maintain using Scotch Box, I'm willing to assist and facilitate these updates. I've not a clue if there's anything like a pull-request for vagrant boxes; if someone could point me in the right direction on that.

**Comment by guedressel** [comment]
Yep - scotchbox just became obsolete, since I need xdebug for work.
It's not possible to install it through the old PPA anymore.
Rebuilding the whole PHP configuration on to the new directory structure Ondřej proposes in his new PPA is not easy and bloats my Vagrantfile.

**Comment by maxpou** [comment]
@whatnickcodes what is the future of this box?

*If you need some help/maintainer just let me know.*

**Comment by whatnickcodes** [comment]
FYI - Closing this to tidy issues before another big release this week

**Comment by whatnickcodes** [comment]
See: https://github.com/scotch-io/scotch-box/issues/273
