### ISSUE TITLE
No logs

### ISSUE THREAD

**Issue by RomkaLTU** [scotch-io/scotch-box#263]
So I think server logs should be available out of the box or even mapped. Now I can't even find Apache logs on default Scotchbox.  What I wanted to do is: 

`config.vm.synced_folder "./logs/", "/var/log", type: "smb"`

**Comment by RomkaLTU** [comment]
Update: logs disappearing when /var/log/ folder mapped to host. After log folder being mapped I only see postgresql, unattended-upgrades redis_6379.log all empty. Tried default folder map and SMB.

**Comment by maxpou** [comment]
Hi,
I'm not sure that is a good idea to share the Apache/MySQL logs with the host by default.
Most of time, we don't need to watch them. Because, now, modern PHP Framework have their own logs system ([monolog](https://github.com/Seldaek/monolog)). If you use Scotchbox for NodeJS applications, logs can be inside the console for a development environment.

If you really need this logs, you have tools like **vi** inside the box. Or you can use the usuals `| tail / grep` pipes as well.

**Comment by RomkaLTU** [comment]
Vagrant vvv have this feature and sometines it helps to catch some odd errors when you can't see it on screen. I faced this problem with wordpress when i could't catch error, so I needed to digg log files. And I absolutely can't see what bad/wrong about sharing log files with host, it's dev enviroment nothing more.

**Comment by maxpou** [comment]
Hi,

[vvv box](https://github.com/Varying-Vagrant-Vagrants/VVV) is only focus on Wordpress PHP CMS. This CMS is one of the last PHP tool which not use modern PHP Tools. Also, Scotchbox is a box for PHP, Ruby and NodeJS developpement. Today, almost all framework/CMS use logging system libraries (even those in Ruby, NodeJS).
It's like the debate which claim to add PHPMyAdmin in this box. It be cannot because Scotch box must stay a clean box (as possible). This is why, according to me, it's not a good idea to add this feature in this box.
In a second hand, if you develop with Winsows OS, it's better to read logs with Unix CLI tools (vi, tail/grep pipes)... especially files with thousands and thousands lines !!!

If you need to adapt this box, it's up to you to fork and adapt this box. [I did it](https://github.com/maxpou/scotch-box) for my needs...

**Comment by whatnickcodes** [comment]
Hey @RomkaLTU nice idea here but I don't think it's a good idea for the end goal of this box.
