### ISSUE TITLE
Anyone else experiencing extremely slow loading times on Wordpress?

### ISSUE THREAD

**Issue by twocatszerokarma** [scotch-io/scotch-box#269]
It's taking ~10 seconds for my pages to load.
I'm running Windows 10, have nfs on in the vagrant file and have tried just about every solution I've found online. I've also tried increasing my virtualbox's memory and CPU usage. My laptop is running on 16gb RAM and an i7 processor so I don't think this problem is related to my machine (I experience this on my other machine as well).
Can anyone help with this?

**Comment by maxpou** [comment]
You have a cache system on your Wordpress ? It's a file cache system?

Because Vagrant is very slow with a Windows host, especially when you need to write on a lot of files. I wrote a blog post to improve Symfony application on Vagrant Box. I know Wordpress doesn't run on Symfony components, but there is some fews tips here.

http://www.maxpou.fr/vagrant-symfony-windows/

Take a look and tell me if it's better !

**Comment by smutek** [comment]
See #144 - This helped me. 

My vagrant file when using ScotchBox looks like this - 

```
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

    config.vm.box = "scotch/box"
    config.vm.network "private_network", ip: "192.168.33.10"
    config.vm.hostname = "scotchbox"
    config.vm.synced_folder ".", "/var/www", :mount_options => ["dmode=777", "fmode=666"]

    config.vm.provider "virtualbox" do |v|
      v.memory = 512
      # v.cpus = 2
    end

        # Fix for slow external network connections
    config.vm.provider :virtualbox do |vb|
      vb.customize ['modifyvm', :id, '--natdnshostresolver1', 'on']
      vb.customize ['modifyvm', :id, '--natdnsproxy1', 'on']
    end

end
```

**Comment by whatnickcodes** [comment]
Thanks and closing this. I know on Mac, Vagrant is always slow on my beast machine unless I use NFS.
