### ISSUE TITLE
Can't access sub-directories on local website

### ISSUE THREAD

**Issue by remminator** [scotch-io/scotch-box#315]
I'm having issues with the website I'm trying to work with.

I can bring up the index just fine - the main index also works fine.

What I can't do is going to any of the Anchor CMS sub-directories.

The directory of the setup looks abit like this:

public
-anchor
--anchor
--composer.json
--composer.lock
--content
--index.php
--install
--license.md
--readme.md
--system
--themes
--vendor
-index.php
README.md
Vagrantfile

Images: http://imgur.com/gallery/XyVIT

**Comment by xAvarice** [comment]
You'll probably want Apache configuration, but you're going to have a nightmare of a time as this is nowhere near as good as Homestead - and yet Homestead is free.

**Comment by whatnickcodes** [comment]
Not really sure what the issue is here. Maybe share some more info?

Tons of good Vagrant alternatives exist if you can't get this working here. These are just Vagrant Box:

* https://github.com/fideloper/Vaprobash
* https://laravel.com/docs/5.4/homestead
* https://github.com/Varying-Vagrant-Vagrants/VVV
* https://puphpet.com/
