### ISSUE TITLE
MailCatcher : mail() don't send mail.

### ISSUE THREAD

**Issue by uvaat** [scotch-io/scotch-box#322]
Hello, 

I would like to send mail in my project.

I start Mailcatcher with

```
mailcatcher --http-ip=0.0.0.0
```
I have a good response

```
MailCatcher runs as a daemon by default. Go to the web interface to quit.
```

but when i start the `mail()` function, no mail sending.

```
$msg = 'TestingMail';
mail('test@test.com', 'Test email', $msg);
```
Can you help me pease ?

**Comment by peterbournecommunications** [comment]
Getting this too.

**Comment by peterbournecommunications** [comment]
For me sendmail wasn't installed... phpinfo() was showing a path to sendmail - but send mail didn't exist there. So even the most basic PHP mail() command failed.

Actually installing sendmail solved the problem - sort of... my virtual box started actually sending proper emails - VERY SLOWLY. So, not ideal. I'd rather it emulated sending them so I can check the output via MailCatcher....

Will destroy the box, provision it again, set the PHP 7.0 user.ini file to point at the IP address for SMTP and port 1025 for smtp_port (as I've read elsewhere), and see what that gets me....

**Comment by peterbournecommunications** [comment]
Upgraded to the Pro version - that's solved the issue it seems - well worth the $15... hopefully its not caused me other unforeseen upgrade issues. Probably wirth the pain long-term!

Thanks for a great product Nick!

**Comment by oliward** [comment]
So I resolved this without using sendmail, by fixing mailcatcher.

Steps to follow:
1. `vagrant ssh` to SSH into your box
2. `sudo apt-get update` to ensure your package lists are up to date
3. `sudo apt-get install ruby` to install ruby
4. `sudo sh -c "echo 'sendmail_path = /usr/bin/env /home/vagrant/.rbenv/shims/catchmail -f dev@scotchbox.local' >> /etc/php/7.0/apache2/conf.d/20-mailcatcher.ini"` to add a new PHP .ini file setting the sendmail_path to use catchmail
5. Finally you can run `mailcatcher --http-ip=0.0.0.0` as you would normally do (if you haven't already) and everything should work as it should do

Now, I have no idea how to ask Scotch Box maintainers to alter the box... I guess just leave this issue here and now they have the information to fix it in next update (yes please!).

**Comment by iantearle** [comment]
I've recently had to reinstall scotch-box - obviously installing V3 by default but I cannot get mailcatcher working or mail in general, it certainly used to work. All I get is "Could not execute: /usr/sbin/sendmail -t -i " or "Could not instantiate mail".

**Comment by septoctobre** [comment]
@oliward 
Thanks, your solution worked for me.
You may want to add `sudo sh -c "echo 'sendmail_path = /usr/bin/env /home/vagrant/.rbenv/shims/catchmail -f dev@scotchbox.local' >> /etc/php/7.0/cli/conf.d/20-mailcatcher.ini"` in some situations (cli or cron jobs)

**Comment by whatnickcodes** [comment]
After the next update. Mail Catcher will be deprecated in favor of MailHog. Check the website later for regarding the next update
