### ISSUE TITLE
Newer Version of PHP

### ISSUE THREAD

**Issue by joshpennington** [scotch-io/scotch-box#361]
Are there plans for moving Scotch Box to PHP 7.1 or 7.2? I am starting to find there are things that will not run on 7.0

**Comment by whatnickcodes** [comment]
THIS IS COMING TODAY!

**Comment by sinandomeng** [comment]
Hi @whatnickcodes, I thought PHP 7.1 or higher will be installed out of the box since https://github.com/scotch-io/scotch-box/issues/361#issuecomment-370001557? I just recently installed but I'm still getting PHP 7.0.18-0ubuntu0.16.04.1. See attached image:

![ScotchBox](https://user-images.githubusercontent.com/16571669/54395131-dc5e4280-46e9-11e9-8e10-5dffe49c9eec.PNG)

**Comment by mircocervi** [comment]
same issue!
