### ISSUE TITLE
Scotchbox vm webserver gives timeout from browser on other pcs

### ISSUE THREAD

**Issue by TimvanSteenbergen** [scotch-io/scotch-box#388]
Situation:
- installed vagrant and VirtualMachine on windows 10. 
- downloaded Scotchbox and installed it
- tested by opening a browser on my local pc by visiting 192.168.33.10 works fine :-)

The problem: from any other machine, the browser returns a 'timeout' when visiting 192.168.33.10

Also I added an A-record to my DNS: myname, A, 192.168.33.10. From my pc when visiting myname.mydomain.com, the browers return the expected correct result. Going to myname.mydomain.com from any other pc, phone etc the 'timeout' gets returned.

Is there any setting that I missed?

An ipconfig on my pc shows different subnets for the VirtualBox adapters (.56 and .33 whereas all others have .2):

> Ethernet adapter VirtualBox Host-Only Network:
> 
>    Connection-specific DNS Suffix  . :
>    Link-local IPv6 Address . . . . . : fe80::60c0:5ef0:bbcc:e4c5%31
>    IPv4 Address. . . . . . . . . . . : 192.168.56.1
>    Subnet Mask . . . . . . . . . . . : 255.255.255.0
>    Default Gateway . . . . . . . . . :
> 
> Ethernet adapter VirtualBox Host-Only Network #2:
> 
>    Connection-specific DNS Suffix  . :
>    Link-local IPv6 Address . . . . . : fe80::9dc4:3e84:1688:347f%36
>    IPv4 Address. . . . . . . . . . . : 192.168.33.1
>    Subnet Mask . . . . . . . . . . . : 255.255.255.0
>    Default Gateway . . . . . . . . . :
> 
> Ethernet adapter Ethernet:
> 
>    Connection-specific DNS Suffix  . : home
>    IPv6 Address. . . . . . . . . . . : 2a02:a444:e5f5:1:6416:dd02:6f1f:a80d
>    Temporary IPv6 Address. . . . . . : 2a02:a444:e5f5:1:126:5934:6330:659c
>    Link-local IPv6 Address . . . . . : fe80::6416:dd02:6f1f:a80d%18
>    IPv4 Address. . . . . . . . . . . : 192.168.2.37
>    Subnet Mask . . . . . . . . . . . : 255.255.255.0
>    Default Gateway . . . . . . . . . : fe80::c6a3:66ff:fe54:2d7c%18
>                                        192.168.2.254

Should I make the virtual hosts keep the same subnet as the others or is this normal behaviour?

**Comment by kenef** [comment]
Hi Tim,

Please correct me if I'm wrong, but it seems that you have a miss-understanding of what scotchbox is. 

Scotchbox is a LEMP/LAMP stack for Vagrant VIRTUAL environments. A virtual environment means one that is local to your computer only. The server at '192.168.33.10' exists solely on your local computer and thus is not a real webserver capable of providing real web hosting. It is simply to create a mock environment of your intended production environment for purposes of smooth development and deployment. In order for your project to be viewed from another computer, your project needs to exist in a live web server, ex: Godaddy, DigitalOcean, BlueHost, HostGator, SiteGround... etc.

If you'd like to use your Vagrant environment as a temporary "live server" so that you may view your vagrant project from other devices, take a look at "Vagrant Share": https://www.vagrantup.com/docs/share/

Vagrant share allows you to host your project in a Vagrant provided cloud server. This method utilizes a unique url string that will change every time you initiate Vagrant Share. This is not meant to be a hosting solution, but more of a method to test your local project from other devices before launching to staging or production. 

Does this make sense?

**Comment by clotted** [comment]
Or use ngrok :)

**Comment by TimvanSteenbergen** [comment]
Hi Kenef, I do understand what Scotchbox is, all I missed was VM not being adressable from outside it's own host. Vagrant share needs ngrok, a paid service and is only for tests and demos. I will look for another setup. Thanks.
