### ISSUE TITLE
Upgrade box to Ubuntu 18.04

### ISSUE THREAD

**Issue by darthmooguy** [scotch-io/scotch-box#401]
Will you upgrade the boxes (free and pro) to Ubuntu 18.04? It would be pretty great, and the packages would be newer.

**Comment by reddingwebpro** [comment]
Unfortunately, Scotchbox is no longer maintained, and it is using an outdated Ubuntu release which is why you're having problems. Last year I released an updated version called CongacBox which was just updated again today...  It is running the most up to date LTS (long term supported) Ubuntu. You can find it on GitHub at https://github.com/reddingwebpro/cognacbox
