### ISSUE TITLE
Apache doesn't start on boot

### ISSUE THREAD

**Issue by Tyguy7** [scotch-io/scotch-box#48]
Tried update-rc.d apache2 enable, doesn't stick.  Every time I vagrant halt and vagrant up, apache is not running.

**Comment by sboerrigter** [comment]
Why is this issue closed? 

I am having the same problem. I alway have to SSH into to start up apache manually. How can I start up apache automatically when I use `vagrant up`?

**Comment by tjdraper** [comment]
This is definitely still an issue, I am not sure why this issue is closed. What I can’t understand is why it’s not working. Everything seems to be in place in the box for apache to start. When I run `sudo update-rc.d apache2 defaults`, it says: `System start/stop links for /etc/init.d/apache2 already exist.` I’m completely baffled.

The way I have gotten around it is adding this to my vagrant file:

```
# Run a script at every boot
config.vm.provision :shell, path: "vagrant-start.sh", run: "always", privileged: true
```

And vagrant-start.sh has this:

```
#!/usr/bin/env bash

service apache2 restart
```

But this is definitely some issue with the box that I can’t figure out.

**Comment by joepurdy** [comment]
I use this box on a regular basis and have never had this issue. I wonder if it's something specific to your environment or version of Vagrant?

Try running this on a terminal, `vagrant -v && vagrant box list | grep scotch/box && VBoxManage -v`
My output looks like this:

```
Vagrant 1.8.1
scotch/box                (virtualbox, 2.5)
5.0.14r105127
```

It's possible the version of scotch/box isn't up-to-date at version 2.5. If this is the case you can try upgrading the box by running `vagrant box update` from the directory that contains your Vagrantfile for scotch/box.

Alternatively you could just nuke it from orbit by running `vagrant box remove scotch/box && vagrant box add scotch/box`

I'm curious to see why this issue is cropping up for multiple people.

**Comment by tjdraper** [comment]
```
Vagrant 1.7.4
scotch/box              (virtualbox, 2.5)
5.0.14r105127
```

I can try updating Vagrant later today when I have some time — everything else is up to date — but it doesn’t seem like a Vagrant problem. It seems like a problem with Ubuntu not starting Apache on boot.

**Comment by joepurdy** [comment]
Yeah I doubt it's Vagrant TBH. I've used scotch/box back on Vagrant 1.7.2 without issue. I was hoping with how long ago the issue was reported it was just some oddity with an earlier version of the box. 

Best of luck with using it and if you do find anything out do tell. I think your workaround script is probably the only surefire solution for the time being.
