### ISSUE TITLE
Setting Up Multiple Sites

### ISSUE THREAD

**Issue by jonorherrington** [scotch-io/scotch-box#52]
Is there an easy way to set up multiple sites within scotch box or are you limited to only one site? I know that you could obviously install another instance of Scotch Box inside another directory and then edit the vagrantflie. The reason I am wanting to do this is so that I can set up different URLs in the hostfile for the different projects I am working on locally.

**Comment by alphex** [comment]
If you're familiar with ubuntu, you can do this.

You're going to have to mess with the vagrant file to make sure you're shared directory is pointing at a place you can see MANY directories on your localhost.

Then remap the 000-default.conf file to point to the right place for the document root.

Then set a Server Name

Then copy this conf file to a new file, and "sudo a2ensite filename" "sudo service apache2 restart"  ... and you should be good.

(this is the short version from memory)

**Comment by jonorherrington** [comment]
Hey thanks man! 

That is very helpful.

My coworker also gave me some good advice. He recommended that I just set multiple instances up and in my hostsfile just map different urls to that one IP. The idea would be you could only have one instance of the box open (which you should already do this to avoid sucking up your memory).

**Comment by cjduncana** [comment]
[This article](https://scotch.io/bar-talk/announcing-scotch-box-2-0-our-dead-simple-vagrant-lamp-stack-improved) explains how you can set up multiple sites ever since Scotch Box 2.0

**Comment by ncerminara** [comment]
Make sure you note that you can do this but I t's better/recommended to do one project per VM



On February 26, 2016 at 2:35:29 PM EST, Christopher John Duncan Araúz <notifications@github.com> wrote:This article explains how you can set up multiple sites ever since Scotch Box 2.0  —Reply to this email directly or view it on GitHub.

**Comment by ethanbeyer** [comment]
@whatnickcodes I've been wanting to dialog with someone about this exact thing. For YEARS I used MAMP, and in the past 12 months have come around to using Vagrant. It's great, and I totally understand all the benefits of mirroring your production and development environments.

One thing that bothers me about the "one-box-per-project/site" thing is that my project's footprint on my computer balloons from:

- the size of its code

...to:

- the size of its code
- + the vagrant box
- + the database.

A site that *might* be 150MB of code and assets is now weighing in at around 3GB and change.

Then every time my machine backs up to Time Machine it has to back up a new 3GB file because the "VM Disk" has been renamed/re-serialized. That might be unavoidable, and I suppose I could exclude the Virtualboxes, but I *do* like backups.

When all I'm doing is a simple WP build, doesn't it make sense to bundle those builds under the same box to save space?

**Comment by whatnickcodes** [comment]
You definitely could do that and it works for some people.

This is just what I like and recommend. I think it's smart to have a Vagrantfile included in the project's repo. So in say 10 months, anyone can pick up and get going locally in minutes

**Comment by ethanbeyer** [comment]
> anyone can pick up and get going locally in minutes

super valid point. that changes how I look at it!

**Comment by whatnickcodes** [comment]
One of us! One of us!

But seriously glad this has helped you. Thanks

**Comment by ethanbeyer** [comment]
Nah man, thank you.
