### ISSUE TITLE
Add Xdebug

### ISSUE THREAD

**Issue by ClementParis016** [scotch-io/scotch-box#7]
Using this awesome Scotch Box for PHP projects would be more comfortable with Xdebug pre-installed on the VM.
I think it's not too hard to install it manually, but it would be nice to add it by default.

**Comment by bobrocke** [comment]
True. But that's kind of tedious every time I fire up a VM. And using Puppet for just Xdebug adds far too much complication. The pleasure of using Scotch Box is that everything is there already.

**Comment by iamgoodbytes** [comment]
I'd like to add that also for our team we're looking at things like https://github.com/jakubgg/scotch-box4dev and homestead again, because we require xdebug in our dev setup. We'd love to stay with scotch-box if possible because we enjoy it so much :)

**Comment by iamgoodbytes** [comment]
@ClementParis016 @bobrocke I'm also getting errors trying to install xdebug manually, does that work on your scotchbox?
sudo apt-get install php5-xdebug php5-dev

Err http://ppa.launchpad.net/ondrej/php5/ubuntu/ precise/main php5-dev amd64 5.5.17+dfsg-2+deb.sury.org~precise+1
  404  Not Found
Failed to fetch http://ppa.launchpad.net/ondrej/php5/ubuntu/pool/main/p/php5/php5-dev_5.5.17+dfsg-2+deb.sury.org~precise+1_amd64.deb  404  Not Found

**Comment by coolbluethomas** [comment]
Installing xdebug on the vm (excellent fork btw @iamgoodbytes , thank you for that) isn't too bad, but how would you setup phpstorm to work with xdebug? I'm having issues getting my mappings correct.

**Comment by iamgoodbytes** [comment]
Glad you got it to work @coolbluethomas - I tend to use this link as a reference for these settings: http://www.sitepoint.com/install-xdebug-phpstorm-vagrant/ whenever I forget

**Comment by coolbluethomas** [comment]
@iamgoodbytes  was looking at that site as well, allthough for xdebug he wasn't much use since he was using homestead. 

I totally forgot what I added to get phpstorm working itsself. I've added a server with the 192.168.33.10 ip adress, turned on "use path mappings". Then mapped my project folder to /var/www (Absolute path on the server). Validating in phpstorm didn't work, because of some error, just an FYI.

**Comment by mikeschinkel** [comment]
I too would vote for XDEBUG installed by default and made sure it works with PhpStorm.  

BTW, this is failing:

    sudo apt-get install php5-xdebug php5-dev

With:

    Processing triggers for install-info (5.2.0.dfsg.1-2) ...
    E: Failed to fetch http://ppa.launchpad.net/ondrej/php5-5.6/ubuntu/pool/main/p/php5/php5-dev_5.6.14+dfsg-1+deb.sury.org~trusty+1_amd64.deb  404  Not Found

    E: Failed to fetch http://ppa.launchpad.net/ondrej/php5-5.6/ubuntu/pool/main/x/xdebug/php5-xdebug_2.3.2-1+deb.sury.org~trusty+1_amd64.deb  404  Not Found

**Comment by ncerminara** [comment]
Unfortunately, I still don't think I will add this.

Do:

```
sudo apt-get update
sudo apt-get upgrade
sudo apt-get install php5-xdebug php5-dev
```

**Comment by mikeschinkel** [comment]
> Unfortunately, I still don't think I will add this.

Understood. 

Just FYI, what I was looking for was a box I can point people to and say _"That will just work."_  

> Do:...

Unfortunately that is not enough, at least not enough to get PhpStorm working. You also need some if not all of these:

    xdebug.remote_enable=1
    xdebug.remote_connect_back=1
    xdebug.remote_port=9000
    xdebug.ide_key=PHPSTORM

Hope this helps others.

**Comment by ncerminara** [comment]
Super helpful. Thanks

**Comment by coolbluethomas** [comment]
Could just create a fork for that and keep those settings in there?

**Comment by ncerminara** [comment]
Fork doesn't really make sense because this is a base box (not a bunch of provisioning scripts).

I think what would be best is if we had a shell script to provision and set all this up on `vagrant up`.

We can just dump this in our docs and make it well known if anyone wants to take point

**Comment by iamgoodbytes** [comment]
+1 for adding this to the scotchbox docs. Thanks @ncerminara

**Comment by courtney-miles** [comment]
I half expected that it may have setup Xdebug the way Composer recommends at [Xdebug impact on Composer](https://getcomposer.org/doc/articles/troubleshooting.md#xdebug-impact-on-composer).

I expected this box would be used mostly by developers for development and so Xdebug would be in high demand.

> I think what would be best is if we had a shell script to provision and set all this up on vagrant up.

I agree that this would be a good option as I'm sure a lot of people need their own variations.

**Comment by mikeschinkel** [comment]
@courtney-miles We were frustrated by ScothBox's lack of support for XDEBUG, so frustrated in fact that we decided to [**build our own box (WPLib Box)**](/wplib/wplib-box/) for WordPress developers and start promoting it, although it should work for most PHP use-cases.  It has XDEBUG working _"out-if-the-bo_, so to speak.

**Comment by whatnickcodes** [comment]
Awesome! We encourage it: https://scotch.io/tutorials/how-to-create-a-vagrant-base-box-from-an-existing-one

Scotch Box is meant to be super vanilla and largely targeted for beginners. It's also by design to have absolutely zero dependencies so things break less with updates and stuff (note: WPLib has vagrant-plugins, etc. Not a bad thing, just a different purpose than Scotch Box). @mikeschinkel check out this plugin https://github.com/fgrehm/vagrant-cachier

For now, Xdebug is still going to stay out of the box. It's harder for people confused by it to uninstall it, than people who know how to use to install it. I think that's completely fair and reasonable.

**Comment by whatnickcodes** [comment]
Also! Just a quick note in case anyone is confused about a WP specific box versus Scotch Box from above ^

Scotch Box is LAMP. WordPress runs on LAMP. WordPress and Scotch Box are basically best friends. Also WP-CLI is installed (but needs an update).

You can install WP on Scotch Box in like 5 seconds: https://scotch.io/bar-talk/announcing-scotch-box-2-5#installing-wordpress.

```
cd my/favorite/folder/for/storing/projects
git clone https://github.com/scotch-io/scotch-box my-new-wordpress-project
cd my-new-wordpress-project
vagrant up
vagrant ssh
cd /var/www/public
rm index.php
git clone https://github.com/WordPress/WordPress --depth=1 .
```

**Comment by mikeschinkel** [comment]
> _Awesome! We encourage it: https://scotch.io/tutorials/how-to-create-a-vagrant-base-box-from-an-existing-one. Anyone can customize and create their own "scotch box" in minutes with absolutely zero effort._

Great, thanks!  We decided to use Packer and start with Ubunutu 14.04 LTS, but your article is definitely one we should link to for people interested in extending ours too.

> _Scotch Box is meant to be super vanilla and largely targeted for beginners._

Cool.  

We are trying to straddle both beginners _(by making the initial success experience as easy as possible)_ and advanced users _(by offering tons of flexibility and power, though much of which is still just planned)_ but optimized for WordPress.  So while our current box may work for Drupal, Symfony, etc, it won't be optimized for any of them.  

We will just have to see if we can pull off both ends of the WordPress spectrum. :-)

> _It's also by design to have absolutely zero dependencies so things break less with updates and stuff_

What are examples of dependencies as you are thinking of it?  You do require Vagrant and VirtualBox or equivalent, right?  

Do you mean dependencies inside the box too, or just outside the box?

> Speaking of, our instructions currently require Composer and a few Vagrant plugins but that was just to get us started; we'll soon remove Composer as a requirement and we are writing our own Vagrant plugin that I would not be an external dependency.

> @mikeschinkel check out this plugin https://github.com/fgrehm/vagrant-cachier

That's cool, but really only beneficial for Vagrantfile that have provisioning scripts, right?  

> _For now, Xdebug is still going to stay out of the box. It's harder for people confused by it to uninstall it, than people who know how to use it to install it. I think that's completely fair and reasonable._

Good plan.  Like you implied, we are targeting different groups and use-cases and can easily co-exist.  We have plans to make WPLib Box the best solution for WordPress local development and eventually the best solution for deployment. That is definitely different that being framework-agnostic LAMP stack targeting beginners.

> Also! Just a quick note in case anyone is confused about a WP specific box versus Scotch Box from above ^ Scotch Box is LAMP. WordPress runs on LAMP. WordPress and Scotch Box are basically best friends. Also WP-CLI is installed (but needs an update). You can install WP on Scotch Box in like 5 seconds: https://scotch.io/bar-talk/announcing-scotch-box-2-5#installing-wordpress.

To clarify the alternative, [**WPLib Box**](https://github.com/wplib/wplib-box) serves WordPress as delivered, complete with a LEMP Stack: Ubuntu Linux, NGINX, MySQL, and PHP and a pre-installed database, Redis for persistent object-caching, several development-related plugins, `composer.json` for professional development,  PHP 5.6, and WP-CLI preinstalled.  

And [by the end of this week version `0.10.7`](https://github.com/wplib/wplib-box/issues?q=milestone:0.10.7) will _add_ PHP 7.0, automatic database dump (backup) to host `/sql` directory, Node/NPM/Gulp/Grunt/Bower/Yoeman, _"On File Action"_ scripts _(basically file watchers)_, Gearman Message Queue+Task Runner, and MailCatcher.  Plans the version after will have an API for doing things like adding sites to the box, and an initial pass at a CLI and more.

If nothing else though, it has been a fun project for my team to work on. :-)

**Comment by whatnickcodes** [comment]
Sounds fun and cool! Email me nick@scotch.io and I'll have our blog tweet it. Also don't want this thread getting off topic too much!

**Comment by smutek** [comment]
> Scotch Box is meant to be super vanilla and largely targeted for beginners.

Dead horse and all that, but I've found that the best tools for me have been the ones that allow me to grow into them over time.

Learning how to use Xdebug was game changing for me. It seems like Xdebug is something that would not add complexity because a user won't even know it's there until they want to use it.
 
It would stay out of the way of beginners, but would be great for them to have once they are ready to use it. VVV's implementation is pretty good in my opinion, in order to use it you have to ssh into the bux and run `xdebug_on`. 

I do mostly WordPress development and I've been looking for a lighter weight alternative to VVV. I'd like to have one box per project as well as a box that offers more flexibility. Scotch is perfect - but the amount of config up front to get the box the way I'd require (mainly this boils down to having to install Xdebug for each project) prohibits me from adopting Scotch for my day to day.

That said, I respect your philosophy and will look into either forking scotch or setting up my own box tailored to my departments needs. 

Thanks for the great tools.

**Comment by jonathanbossenger** [comment]
I know this has been closed, but I'd like to leave this hear for anyone who comes across this url. 

https://medium.com/@felladrin/installing-xdebug-on-scotch-box-and-integrating-it-with-phpstorm-webstorm-5b1f96ce69#.fr7vyawd4

100% got me setup with xdebug and PHP Storm on Scotchbox.

**Comment by pouyada** [comment]
i still have this problem while installing xdebug . 
sudo apt-get install php5-xdebug 


E: Failed to fetch http://ppa.launchpad.net/ondrej/php5-5.6/ubuntu/pool/main/p/php5/php5-dev_5.6.14+dfsg-1+deb.sury.org~trusty+1_amd64.deb  404  Not Found

E: Failed to fetch http://ppa.launchpad.net/ondrej/php5-5.6/ubuntu/pool/main/x/xdebug/php5-xdebug_2.3.2-1+deb.sury.org~trusty+1_amd64.deb  404  Not Found

**Comment by smutek** [comment]
Hey @pouyada, I have a fork going that installs xDebug. There's not much too it really, just a small shell script that installs xDebug, it follows the steps in the link that @jonathanbossenger posted. 

Here's a link to the shell script if you want to check it out - https://github.com/smutek/sassscotch/blob/master/vagrant_bootstrap/bootstrap.sh

**Comment by raisen** [comment]
I'm having the same problem that @pouyada is having, and @smutek failed as well. I think something is wrong with this APT source:

`deb http://ppa.launchpad.net/ondrej/php5-5.6/ubuntu trusty main`

located at `/etc/apt/sources.list.d` ?

**Comment by pouyada** [comment]
@smutek's script did not work also for me. Anyway i resolved this problem by modifying sources list located in : /etc/apt/sources.list.d
1- cd /etc/apt/sources.list.d
2- find any file which name contains php 5.6 or 5_6 ( i had 2 files like this ) 
3- open those files using nano ( sudo nano filename ) 
4- any file contains just 2 lines . comment all lines by adding a # and then save the file ( ctrl + o )
5 - close  the nano ( ctrl x ) 

and then 
sudo apt-get install php5-xdebug php5-dev

**Comment by smutek** [comment]
@pouyada @raisen I just tried as well and am also getting the APT source issue. Sorry about that, it was working for me previously.

**Comment by pouyada** [comment]
yes because you are doing sudo apt-get update at the beginning of the script, and this issue does not allow.

**Comment by daviddarke** [comment]
Getting the same APT issue as @pouyada @raisen @smutek :(

**Comment by smutek** [comment]
I think the issue is that the PPA is obsolete. See: http://askubuntu.com/questions/741913/php7-0-dev-installation-fails-on-ubuntu-14-0-4

I was able to get it installed by following [these steps](http://askubuntu.com/a/744382) from the same Ask Ubuntu thread, then installing Xdebug, then restarting the server. 

So all steps  -

- Get rid of the old PPA
`sudo apt-get install ppa-purge`
`ppa-purge ppa:ondrej/php5-5.6`

- Add the current PPA
`sudo add-apt-repository ppa:ondrej/php`
- Update
`sudo apt get update`
`sudo apt-get upgrade`
`sudo apt-get autoremove`
- Install Xdebug
`sudo apt-get install php5-xdebug`
- Configure Xdebug
`sudo vim /etc/php5/apache2/conf.d/20-xdebug.ini`
  - add to the file, save and close
    ```
    zend_extension=xdebug.so
    xdebug.remote_enable=1
    xdebug.remote_connect_back=1
    xdebug.remote_port=9000
    xdebug.remote_host=192.168.33.10
    ```
- Restart apache
`sudo service apache2 restart`

I updated my script, and my fork, and I am able to `vagrant up`, test, and verify with PHPStorm that Xdebug  is working as expected. 

Problems and Disclaimers are:

1. I have no idea what I'm doing.
2. Other things may now be broken, I have no idea, YMMV.
3. Somewhere along the line one of these processes creates an empty html directory for some reason. Safe to delete, but testament that I have no idea what I'm doing.
4. Running the updates and upgrade takes a really long time. 

But, Xdebug is working! 

Unfortunately Xdebug is working at the expense of the speed, convenience, ease of use and all the other things that drew me to ScotchBox in the first place (and possibly at the expense of breaking other things.) 

I think the main underlying problem is that the ScotchBox itself needs an update. 

It was last updated in November of 2005 and doesn't seem to be regularly maintained. There's been updates, but nothing major, and the [base box hasn't been updated for over a year](https://atlas.hashicorp.com/scotch/boxes/box/versions/2.5). 

Again, no idea what I'm doing, but if updating everything makes it possible to install Xdebug then it seems to follow that the base box probably needs a refresh. Another example, WP-CLI was added in November (but no Xdebug because it will "throw beginners of their game"?) but the WP-CLI version that ships with the box is out of date and isn't compatible with the current version of WordPress. So it needs to be immediately updated in order to be used.

I don't know, Scotch isn't really a solution for me anymore and rather than trying to make it work for me I think I'd personally be better off learning how to make my own box.

**Comment by smutek** [comment]
See also - 

#273 
#257 
https://www.patreon.com/posts/now-is-time-to-7009050

**Comment by pouyada** [comment]
@daviddarke follow the Instructions that i said in my last comment . il will work 100% . 
i dont know the about @smutek  instructions and I can't try that because i dont use scotch box any more. it was so annoying .

**Comment by daviddarke** [comment]
Thanks for this :)

**Comment by briannambui** [comment]
In regards to adding new PPA...

Note: If your system's locale is set to anything other than UTF-8, adding the PPA may fail due to a bug handling characters in the author's name. As a workaround, you can install language-pack-en-base to make sure that locales are generated, and override system-wide locale settings while adding the PPA:

sudo apt-get install -y language-pack-en-base
sudo LC_ALL=en_US.UTF-8 add-apt-repository ppa:ondrej/php

**Comment by raisen** [comment]
@smutek, thanks for providing these steps.

 I followed them, got no errors, but for some reason, xdebug.so is installed into `/usr/lib/php5/20121212`, whereas the server is expecting to be installed at `/usr/lib/php5/20131226`. Any ideas why?

**Comment by Zykhatslover** [comment]
Same issue here :/

**Comment by iamgoodbytes** [comment]
@smutek thanks for these instructions, installing xdebug has cost me several hours in scotch box. I had a good process going, but I needed your instructions in order to get rid of the old PPA recently. 

I'm also looking for alternatives because of this, but since I'm a Laravel developer I'll probably switch to homestead for my next project. I'm also really grateful for the time scotchbox has saved me over the years. Right now, unfortunately it's costing me more and more time just to get up and running with xdebug.

**Comment by Zykhatslover** [comment]
@iamgoodbytes I ran into the same problem (as I commented above) and I found out that puppet (via puPHPet) vas a really good alternative!  [Just visit this link and follow the steps](https://puphpet.com) .  

It's easy to use, easy to maintain, easy to share with others, seriously it rocks :o you can easily configure multiple box (with, let's say another PHP version), virtual hosts etc, it's a bit tougher than scotchbox but at least it's doable :).  As for Laravel, just make sure you "installed" all the PHP mods and you'r good to go (it worked for my Laravels as well as for my Symfonys projects!).

**Comment by iamgoodbytes** [comment]
@Zykhatslover puPHPet is indeed a good alternative, but I'm a bit concerned about maintenance of those boxes and don't feel like doing that myself. Right now, I just switched over to Homestead (being a Laravel developer) and xdebug just works out of the box. You only need to set your path mappings if you use phpstorm, but that's just a few seconds work. Anyway, I have used scotchbox for years and have really enjoyed it and I respect the decision to not include xDebug.

**Comment by Zykhatslover** [comment]
@iamgoodbytes Well it's not that hard to configure and I don't think it's hard to maintain but Homestead is a good alternative too.  I went for that for my Laravels projects as well but I don't really like the fact that Nginx is preferred to Apache (I haven't been too far into Homestead since all I needed was a running server for Laravel but maybe you can configure it so it uses Apache instead I don't know).  Anyways Scotchbox will probably get back sooner or later with a new version :)!

**Comment by robme** [comment]
@mikeschinkel how did you fix the problem with the packages not being found?

When I run

```
sudo apt-get update
sudo apt-get upgrade
sudo apt-get install php5-xdebug php5-dev
```

I get this after the install command:

```
Err http://ppa.launchpad.net/ondrej/php5-5.6/ubuntu/ trusty/main php5-dev amd64 5.6.14+dfsg-1+deb.sury.org~trusty+1
  404  Not Found
Err http://ppa.launchpad.net/ondrej/php5-5.6/ubuntu/ trusty/main php5-xdebug amd64 2.3.2-1+deb.sury.org~trusty+1
  404  Not Found
Err http://ppa.launchpad.net/ondrej/php5-5.6/ubuntu/ trusty/main dh-php5 all 0.2+deb.sury.org~trusty+2
  404  Not Found
Err http://ppa.launchpad.net/ondrej/php5-5.6/ubuntu/ trusty/main pkg-php-tools all 1.21+deb.sury.org~trusty+1
  404  Not Found
E: Failed to fetch http://ppa.launchpad.net/ondrej/php5-5.6/ubuntu/pool/main/p/php5/php5-dev_5.6.14+dfsg-1+deb.sury.org~trusty+1_amd64.deb  404  Not Found

E: Failed to fetch http://ppa.launchpad.net/ondrej/php5-5.6/ubuntu/pool/main/x/xdebug/php5-xdebug_2.3.2-1+deb.sury.org~trusty+1_amd64.deb  404  Not Found

E: Failed to fetch http://ppa.launchpad.net/ondrej/php5-5.6/ubuntu/pool/main/d/dh-php5/dh-php5_0.2+deb.sury.org~trusty+2_all.deb  404  Not Found

E: Failed to fetch http://ppa.launchpad.net/ondrej/php5-5.6/ubuntu/pool/main/p/pkg-php-tools/pkg-php-tools_1.21+deb.sury.org~trusty+1_all.deb  404  Not Found
```

**Comment by mikeschinkel** [comment]
@robme It's been over a year since I last looked at how to do that so don't actually remember. We've built our own box that has XDEBUG baked in called [WPLib Box](https://github.com/wplib/wplib-box) to solve exactly that problem.  It is named to appeal to WordPress developers but really is just a general-purpose PHP box.

**Comment by btantlinger** [comment]
Please just add xdebug to scotchbox and make us all happy.  I don't get your reasoning that it's "for beginners."  It's not like you're forced to use xdebug.   You could also add a switch to enable/disable it similar to what Laravel homestead does.  E.g xon to turn on xdebug,  xoff to turn it off.

**Comment by jonathanbossenger** [comment]
Everyone moaning about wanting to add xDebug to Scotch Box, please read @whatnickcodes comments here #244 

If you want it, make it happen. Fork the project, figure out the problem and release it back to the world. Or do what @mikeschinkel has done and build and release your own box. Complaining that a feature you want is not available in an open source project is like peeing against the wind. Be the change and do something about it yourself. </rant>

@whatnickcodes please close this issue.

**Comment by Zykhatslover** [comment]
I'll give a +1 to that even tho I believe a lot of people would love to fix this issue.  They (we :p) just don't have the skills to do it. 

By the way I'll repeat it, you guys should give a try to [puPHPet](www.puphpet.com).  It's quite easy to configure, it comes with xdebug out of the box (you can disable it if you want).  You can configure it as much as you want and once it's all set, there's nothing else to do..  I personally wouldn't use scotchbox anymore after dealing with puPHPet.

That's my 2 cent :-).

**Comment by btantlinger** [comment]
I actually do use puPHPet for some projects, but maintaining those puPHPet boxes over the long haul doesn't work so well in my experience.  E.g, I'll create a box for what I need, save the yaml file... but then the yaml file often breaks with newer versions of puPHPet as things change.   So I end up having to configure a new puphpet box every time, which gets tedious.

This is one of the really nice things about scotchbox.  I don't have to worry about any of that,  just issue a vagrant up, and I'm on my way without expending mental cycles on configuring a dev environment.   Sadly, scotchbox is beginning to show its age, and the lack of xdebug is starting to be a deal-breaker.

**Comment by Zykhatslover** [comment]
Well I've suffered from 1 bug so far... on both scotch box and puPHPet, both due to some kind of upgrade, but puPHPet took me 20mn to fix it (just had to create my boxes from scratch) and it works fine now, I don't even use the UI anymore and I edit the config.yaml directly.

But yeah I got your point : a preconfigured package is better.. but I can't develop anymore without xdebug so I have to find another way.

All this to say that puPHPet can be a good workaround :).

**Comment by mikeschinkel** [comment]
@btantlinger Just curious, what are you using Scotch Box for?  What type of development?  Drupal, WordPress, Laravel, other, vanilla PHP?

**Comment by btantlinger** [comment]
Various types, but with scotchbox mostly WP -  I did take a look at your WPLibBox,  but I'd rather use apache in my dev environment as that is what I mostly deploy to.

**Comment by mikeschinkel** [comment]
@btantlinger We will be supporting Apache in the near future...

**Comment by btantlinger** [comment]
@mikeschinkel awesome to hear, I will keep an eye out for it.  Looks very cool!

**Comment by mikeschinkel** [comment]
@btantlinger  https://github.com/wplib/wplib-box/milestone/20

**Comment by Das123** [comment]
@smutek Thanks. Your longish post from Nov 28 got it working for me. Much appreciated. There were a few things not quite working if you update your post:
Need to add 'sudo' to
`sudo ppa-purge ppa:ondrej/php5-5.6`
Hyphen missing in
`sudo apt-get update`
After restart running a check to see it is installed
`php -v`
Thanks again. :)

**Comment by mikeschinkel** [comment]
@btantlinger As promised, WPLib Box now also [**supports Apache**](https://github.com/wplib/wplib-box/blob/master/FAQ.md#how-do-i-switch-from-nginx-to-apache-or-vice-versa).

**Comment by iuriimattos** [comment]
It's simple, start a ssh session then  `sudo apt-get install php-xdebug`
